af-south-1:
  amazonlinux2: ami-0227908b0a0e8f097
ap-east-1:
  amazonlinux2: ami-0a2944230de004ad2
ap-northeast-1:
  amazonlinux2: ami-0220a6b98b70e1279
ap-northeast-2:
  amazonlinux2: ami-05f0b456179f64cce
ap-south-1:
  amazonlinux2: ami-0ff36e1c9fc87b74b
ap-southeast-1:
  amazonlinux2: ami-0cf829f9c4973625a
ap-southeast-2:
  amazonlinux2: ami-0b6e1baf8051c736d
ap-southeast-3:
  amazonlinux2: ami-0ab7e9ed84451c9a5
ca-central-1:
  amazonlinux2: ami-08a859076e1aadedb
eu-central-1:
  amazonlinux2: ami-0812d7c8f1abc0e24
eu-north-1:
  amazonlinux2: ami-0bfa1e6c61e82e4b6
eu-south-1:
  amazonlinux2: ami-04154c8a5ee61adbc
eu-west-1:
  amazonlinux2: ami-076c9bc5be2893a11
eu-west-2:
  amazonlinux2: ami-05e4ed86eaaac596f
eu-west-3:
  amazonlinux2: ami-09f63a3a06d08cac1
me-south-1:
  amazonlinux2: ami-0d7f2bd7b639a7bdf
sa-east-1:
  amazonlinux2: ami-020689e1463efba96
us-east-1:
  amazonlinux2: ami-076c7acfc9e8ee57d
us-east-2:
  amazonlinux2: ami-048b22ce7dcf74123
us-gov-west-1:
  amazonlinux2: ami-0fc9f447d5d08b588
us-west-1:
  amazonlinux2: ami-06c8c34275c6770cf
us-west-2:
  amazonlinux2: ami-094a0fafc1bf73bd6
