amazonlinux2:
  arm64:
    default-name: 'Amazon Linux 2 - ARM64'
    default-description: 'Amazon Linux 2 - ARM64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-00a45e16508ceefa7
      ss-id-suffix: base
      name: 'Software Stack Amazon Linux 2 - ARM64' # override default name
      description: 'Software Stack Amazon Linux 2 - ARM64' # override default description
      min-storage-unit: gb # override default min-storage-unit
      min-storage-value: 10 # override default min-storage-value
    ap-east-1:
    - ami-id: ami-01174e0118c296c37
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-02087d6f3ccd8073f
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-03159e41d5c4d0a31
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0fc81ccb6d411c58b
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-05465ed4133f4f04c
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0f18530afdf50e2cf
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-047b91a0561816728
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0463527f07939f08c
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0965af9995b3a878f
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0cb0c6fa5a3c56cc0
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-06beae21e62330dd0
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-05223a36a9748498d
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0d97fa13ebda706b8
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0e9ca48e27e192f4f
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-01cbb5e0afe310efe
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-03616356ac6a80d87
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0ff3578f8df132330
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-04ed2b27d86c17f09
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-029ae49b68d81e045
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0f36e12deb25112d9
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0bbda02f23a4a8964
      ss-id-suffix: base
  x86-64:
    default-name: 'Amazon Linux 2 - x86_64'
    default-description: 'Amazon Linux 2 - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-04f95a4a3609e4cf3
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-051ec00661c466b27
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-0b069de314c9ab4c4
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-066d41d96fc160063
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-068cda7597e78094b
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-013586750d303f89d
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0336d88ead51a9210
      ss-id-suffix: base
    ap-southeast-3:
    - ami-id: ami-077238a133cf52716
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0300c413e2de1804e
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-041e64b0129bffca9
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0b87edaa84d7c45ce
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-07a10ce489fece5f8
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-038e9cdc714b15936
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0c496e8bea496ed67
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-002e2b155689f6e23
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-090a20e93e6698582
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-058f4e20c17271f68
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-02538f8925e3aa27a
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0ee5c62243ab25259
      ss-id-suffix: base
    us-gov-west-1:
    - ami-id: ami-02332daf4b2e35b71
      default: Y
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0019ad94c6124959d
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-07d59d159373b8030
      ss-id-suffix: base
centos7:
  arm64:
    default-name: 'CentOS7 - ARM64'
    default-description: 'CentOS7 - ARM64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-0002d7a67b2047e67
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-0f18e61452a29247d
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-0a9d0fdaf6eba3b96
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-09e34a2c74d315279
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0b5c298137e260867
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0a8ab25085477038e
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-014dafc35e50da2f5
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-06cadcf5911e61f49
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0a305a7534a53874c
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0703d28356ece347c
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0869c99d1ba8518e8
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-0e2a2f48fffbaa4fa
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-098cdf26bc3c008df
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0286c81df9e81730d
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-0aec6b83245d4ccaf
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-07afdb5b9e57dab5e
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-0b802bd2b502aa382
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-07f692d95b2b9c8c5
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-09748e99ee14e3823
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0db02f65655518c52
      ss-id-suffix: base
  x86-64:
    default-name: 'CentOS7 - x86_64'
    default-description: 'CentOS7 - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-0b761332115c38669
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-09611bd6fa5dd0e3d
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-0ddea5e0f69c193a4
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0e4214f08b51e23cc
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-0ffc7af9c06de0077
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0adfdaea54d40922b
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-03d56f451ca110e99
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0a7c5b189b6460115
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-08b6d44b4f6f7b279
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0358414bac2039369
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0fe3899b62205176a
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-04f5641b0d178a27a
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0b22fcaf3564fb0c9
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-072ec828dae86abe5
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-0ac17dcdd6f6f4eb6
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-02334c45dd95ca1fc
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-00e87074e52e6c9f9
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-00f8e2c955f7ffa9b
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-08d2d8b00f270d03b
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-0686851c4e7b1a8e1
      ss-id-suffix: base
rhel7:
  x86-64:
    default-name: 'RHEL7 - x86_64'
    default-description: 'RHEL7 - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-064aeb2452a82205f
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-0e377c3509b0a1490
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-0073b6113281aa32e
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-04adf7ab262061270
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-01dd6bbea8d062bf3
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-0ee6bfca4452064bc
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0bf7d72cc0b127581
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-0f1c453d5ca1059f0
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-0a62e33b5dcf31c85
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0a32f8cdd314cf493
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0f18d0a883583eaa9
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-06211bde2f9c725e5
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0a8aebd46fb700315
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-07185297899bb7755
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-02f76563b3f70c99d
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-08acb85e5164523d7
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-004fac3d4533a2541
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0bb2449c2217cb9b0
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-085733fd69e77a079
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-027da4fca766221c9
      ss-id-suffix: base
rhel8:
  x86-64:
    default-name: 'RHEL8 - x86_64'
    default-description: 'RHEL8 - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-08a8728b7fbf38c8b
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-0fc4931f101d144f9
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-063c13b7924c62541
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-0f57bdfa637d1ed53
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-002b3a442fc114c66
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-00f323e982aa37be9
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0861840a219b3c751
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-04c26c5f9fd7b0497
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-04a5b6bd429eaf261
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-07f35de48bbe31001
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-05d37a2ba5ea8d64a
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-00d214492e15ccbce
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-0e5b5870f6a07759d
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-07ad907cba66e96ff
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-052613cf395c754e3
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-002292a2992e8943a
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-08b6e3ac65326f664
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-0b530377951178d6b
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0f96932b1332fb4ab
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-07c872995aa27ace4
      ss-id-suffix: base
rhel9:
  x86-64:
    default-name: 'RHEL9 - x86_64'
    default-description: 'RHEL9 - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 10
    default-min-ram-unit: gb
    default-min-ram-value: 4
    af-south-1:
    - ami-id: ami-046243dd08fb2a485
      ss-id-suffix: base
    ap-east-1:
    - ami-id: ami-06a43df7e9a97d129
      ss-id-suffix: base
    ap-northeast-1:
    - ami-id: ami-0477d3aed9e98876c
      ss-id-suffix: base
    ap-northeast-2:
    - ami-id: ami-004b403708f61ecd8
      ss-id-suffix: base
    ap-south-1:
    - ami-id: ami-008b85aa3ff5c1b02
      ss-id-suffix: base
    ap-southeast-1:
    - ami-id: ami-02acda7aaa1f944e5
      ss-id-suffix: base
    ap-southeast-2:
    - ami-id: ami-0d5c8edc10c17ec35
      ss-id-suffix: base
    ca-central-1:
    - ami-id: ami-081650ae0104087a4
      ss-id-suffix: base
    eu-central-1:
    - ami-id: ami-03cbad7144aeda3eb
      ss-id-suffix: base
    eu-north-1:
    - ami-id: ami-0874ff0d73a3ab8cf
      ss-id-suffix: base
    eu-south-1:
    - ami-id: ami-0f50f92361e5f9c89
      ss-id-suffix: base
    eu-west-1:
    - ami-id: ami-013d87f7217614e10
      ss-id-suffix: base
    eu-west-2:
    - ami-id: ami-07fb9d5c721566c65
      ss-id-suffix: base
    eu-west-3:
    - ami-id: ami-0d767e966f3458eb5
      ss-id-suffix: base
    me-south-1:
    - ami-id: ami-0de3e6d26549e7ee6
      ss-id-suffix: base
    sa-east-1:
    - ami-id: ami-025379b05972d9189
      ss-id-suffix: base
    us-east-1:
    - ami-id: ami-026ebd4cfe2c043b2
      ss-id-suffix: base
    us-east-2:
    - ami-id: ami-02b8534ff4b424939
      ss-id-suffix: base
    us-west-1:
    - ami-id: ami-0dc8c969d30e42996
      ss-id-suffix: base
    us-west-2:
    - ami-id: ami-00aa0673b34e3c150
      ss-id-suffix: base
windows:
  x86-64:
    default-description: 'Windows - x86_64'
    default-name: 'Windows - x86_64'
    default-min-storage-unit: gb
    default-min-storage-value: 30
    default-min-ram-unit: gb
    default-min-ram-value: 4
    ap-northeast-1:
    - ami-id: ami-03e9af94a9320bdf6
      ss-id-suffix: base
    - ami-id: ami-0f73f5c42d0a2a659
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0744247159c640e32
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    ap-northeast-2:
    - ami-id: ami-0348704713bf023f6
      ss-id-suffix: base
    - ami-id: ami-0cc1538dd3712c9bc
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    ap-south-1:
    - ami-id: ami-0307cbf9fc4c96c3e
      ss-id-suffix: base
    - ami-id: ami-0bed7f8476b0a0f49
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    ap-southeast-1:
    - ami-id: ami-04a4a643aca2fb749
      ss-id-suffix: base
    - ami-id: ami-0e190f8939a996caf
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    ap-southeast-2:
    - ami-id: ami-0c9120089f9f6eb5d
      ss-id-suffix: base
    - ami-id: ami-0e190f8939a996caf
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    ca-central-1:
    - ami-id: ami-016ca4a1fb96ec103
      ss-id-suffix: base
    - ami-id: ami-02ce5abc7648ae028
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-024f599e25b98b213
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    eu-central-1:
    - ami-id: ami-004fd86583eb494ee
      ss-id-suffix: base
    - ami-id: ami-01f877801cd06f23f
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0649343058a73af62
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    eu-north-1:
    - ami-id: ami-0db5739e8f768b605
      ss-id-suffix: base
    - ami-id: ami-0745b0d998883f154
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    eu-west-1:
    - ami-id: ami-01643440d0d3abc52
      ss-id-suffix: base
    - ami-id: ami-0b79b4e3a40bdf60e
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0bb7bad82b320fcca
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    eu-west-2:
    - ami-id: ami-05a79fae5322ddf7b
      ss-id-suffix: base
    - ami-id: ami-049344b657f4fb45c
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0be3d5c1d59782960
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    eu-west-3:
    - ami-id: ami-09f72979d087b7ef8
      ss-id-suffix: base
    - ami-id: ami-0395cf74387ac6b14
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    sa-east-1:
    - ami-id: ami-082e6f2a2f1b98d29
      ss-id-suffix: base
    - ami-id: ami-0cce9af6bed94ceec
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    us-east-1:
    - ami-id: ami-0fceec18b58bfda68
      ss-id-suffix: base
    - ami-id: ami-05d3c1e8d7f2401bc
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0f32d32b08fe60259
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    us-east-2:
    - ami-id: ami-0d8ebcdbdb1b96378
      ss-id-suffix: base
    - ami-id: ami-00f5db175bcde7485
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0ac825a0cfb844c65
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    us-west-1:
    - ami-id: ami-00d8bcd4ea61ab790
      ss-id-suffix: base
    - ami-id: ami-05572dee4d1b36e50
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
    us-west-2:
    - ami-id: ami-05da7901ff681da6e
      ss-id-suffix: base
    - ami-id: ami-07e2aac81c0943443
      description: Windows - AMD
      gpu-manufacturer: AMD
      name: Windows - AMD
      ss-id-suffix: base-amd
    - ami-id: ami-0dd677b93d5737213
      description: Windows - NVIDIA
      gpu-manufacturer: NVIDIA
      name: Windows - NVIDIA
      ss-id-suffix: base-nvidia
